# Generated by Django 4.1.7 on 2023-05-11 18:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Commandee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cmd', models.DateField(default=datetime.date.today)),
                ('etat_cmd', models.CharField(choices=[('ATT', 'En attente'), ('ENC', 'En cours de traitement'), ('TER', 'Terminé')], default='ATT', max_length=3)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_carte', models.CharField(max_length=128)),
                ('montant', models.FloatField()),
                ('date_reglement', models.DateField(default=datetime.date.today)),
                ('commandeC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.commandee')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('prix', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('quantite', models.IntegerField(default=0)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='commandee',
            name='produitP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit'),
        ),
        migrations.AddField(
            model_name='commandee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
